### ISSUE TITLE
setting RPC urls when initializing 

### ISSUE THREAD

**Issue by glitch-txs** [blocto/blocto-sdk#281]
When creating a bloctoSDK instance, would it be possible to pass all RPC and chains we want to potentially use? to avoid using `wallet_addEthereumChain` on the flow? I'm not sure if this makes sense, I'm currently exploring Blocto wallet.

I mean something like this

```ts
import BloctoSDK from '@blocto/sdk'

const bloctoSDK = new BloctoSDK({
    ethereum: {
       1: 'https://mainnet.infura.io/v3/YOUR_INFURA_ID',
       5: 'https://rpc.ankr.com/eth_goerli',
    },
    
    // (optional) Blocto app ID
    appId: 'YOUR_BLOCTO_APP_ID',
});
```

Thanks

**Comment by akira02** [comment]
Yes, technically it's possible. I think it will be great to initial sdk instance and load switchable chains in one move. 
@mordochi How do you think about priority of this api change?

**Comment by mordochi** [comment]
Hi, @glitch-txs, thank you for bringing up this topic!

Our team appreciate this idea and will schedule to implement this enhancement 

Before we've done such updates, you can just configure the chains with `loadSwitchableNetwork`
```js
export const supportedChains = [
  {
    name: "Ethereum Mainnet",
    chainId: "0x1",
    rpcUrls: ["https://mainnet.infura.io/v3/ef5a5728e2354955b562d2ffa4ae5305"],
    environment: "mainnet",
  },
  {
    name: "Arbitrum Mainnet",
    chainId: "0xa4b1",
    rpcUrls: ["https://arb1.arbitrum.io/rpc"],
    environment: "mainnet",
  },
  ...
];

const bloctoSDK = new BloctoSDK({
  // Default chain
  ethereum: {
    chainId: "0x1",
    rpc: "https://mainnet.infura.io/v3/ef5a5728e2354955b562d2ffa4ae5305",
  },
  appId: process.env.REACT_APP_DAPP_ID,
});

bloctoSDK.ethereum.loadSwitchableNetwork(supportedChains);
```
Hope this will serve your use case for now :)

**Comment by akira02** [comment]
Thanks for the idea. I've designed a new config structure, starting from v0.9.0. Now, we can load multiple chain settings when creating a BloctoSDK instance.
```ts
const bloctoSDK = new BloctoSDK({
  ethereum: {
    defaultChainId: '0x1',
    switchableChains: [
      {
        chainId: '0x1',
        rpcUrls: ['https://mainnet.infura.io/v3/...'],
      },
      {
        chainId: '0xa4b1',
        rpcUrls: ['https://arb1.arbitrum.io/rpc'],
      },
      ...
    ],
  },
  
  // (optional) Blocto app ID
  appId: 'YOUR_BLOCTO_APP_ID',
})
```
This structure is more complex but has several advantages. One is compatibility with EIP-3085 AddEthereumChainParameter, and also it provides space to add more config params in the future.

Again, thank you so much for your valuable suggestion regarding our BloctoSDK. We truly appreciate your insightful input.
